### PR TITLE
Playwright docs

### PR DESCRIPTION
**Pull request by aaronhans**
Working on some playwright docs with @zakiya 

They playwright.md is the start of a playbook recording some info useful for writing end to end tests with playwright

The package.json and corresponding test files are there to run the samples

### CODE REVIEW

**Review by chachasikes — COMMENTED** [review]
Q: we are using odi-engineering repo for tests?

**Comment by aaronhans** [comment]
No, not real tests

These are docs on testing

**Comment by aaronhans** [comment]
This is internal facing documentation that is convenient to write and consume in github repo markdown. @zakiya and I thought it worked well here but happy to move it if we have a better location

**Comment by zakiya** [comment]
Capturing some notes here for future documentation:

- `playwright.config.js` is pretty useful. We should document and/or reference it. `headless: true/false` can take the place of `PWDEBUG = 1`
- Users need to be aware of the Page.Locator class
- You can store tests somewhere besides `tests` folder by using `playwright test my/chosen/path/menus.spec.js` commnad

**Pull request merged**
